[package]
name = "knot-nm-dns-update"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
clap = { version = "4.6.6", features = ["unicode", "string", "derive", "env"] }
env_logger = "0.11.11"
http-body-util = { version = "0.1.5", features = ["full"] }
hyper = { version = "1.11.1", features = ["client", "full", "http2", "http1"] }
hyper-util = { version = "0.1.20", features = ["client", "client-legacy", "full", "http2", "http1", "tokio", "tracing"] }
hyperlocal = { version = "0.9.1", features = ["hyper-util"] }
log = "0.4.34"
resolv-conf = "0.7.6"
serde_json = "1.0.151"
sha3 = "0.12.0"
tokio = { version = "1.53.1", features = ["full"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "unwind"
incremental = false
codegen-units = 16
